name: End-to-End Tests

on: [push]

jobs:

  vault-tests:
    name: End-to-end tests for vaults
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Start containers
      working-directory: ./haas/test/add-host/
      run: docker-compose -f docker-compose.yaml up --remove-orphans --abort-on-container-exit --exit-code-from client
